### PR TITLE
Use auto-generated application yaml

### LINKED ISSUE #68: Configuration testing
Figure out a way to make sure that the Golang application data structure always matches the CRD application spec.

### PR DESCRIPTION
**Pull request by ambientsound**
The project [Kubebuilder](https://book.kubebuilder.io/) has a tool called [controller-gen](https://github.com/kubernetes-sigs/cluster-api/tree/master/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen) that can be used to generate the CRD YAML file, using only `types.go` as its input source.

I did some non-invasive preliminary work and the results are promising. Integrating this will eliminate the manual and error-prone task of synchronizing the type specification with the CRD YAML.

Fixes #68

### CODE REVIEW

**Comment by ambientsound** [comment]
Tested compatibility with existing version using:

```
% kubectl get --context dev-fss --namespace default -o yaml app > apps.yaml
% kubectl apply --context gke_kim-tore_europe-north1-a_kimtore -f config/
customresourcedefinition.apiextensions.k8s.io/application.nais.io configured
% kubectl apply --context gke_kim-tore_europe-north1-a_kimtore -f apps.yaml
application.nais.io/ai-lab-named-entity-api created
[--- snip ---]
application.nais.io/webarxaas created
%  
```

rfc @VegarM @KFBI1706 @matsbyfl

**Comment by ambientsound** [comment]
> Looks very good. Might be a good test to deploy naiserator to the gcp test cluster and let it attempt to create all the resources as well?

Good suggestion. Running Naiserator locally yields:

```
{"level":"info","msg":"Starting application synchronization","time":"2019-07-17T11:07:33.314955+02:00"}
E0717 11:07:33.411212   52598 reflector.go:131] pkg/mod/k8s.io/client-go@v0.0.0-20190408172623-b7e8408f656e/tools/cache/reflector.go:99: Failed to list *v1alpha1.Application: the server could not find the requested resource (get applications.nais.io)
```

**Comment by ambientsound** [comment]
Tested Naiserator on a fresh cluster against the `Application` resources currently in `dev-fss/default` and it runs successfully.

**Comment by Kyrremann** [comment]
Fancy

**Pull request merged**
