### PR TITLE
Support startup probes

### LINKED ISSUE #181: Support for startupProbe
Due to slow initial startup of applications, we set a long initialDelay and high failureThreshold values.

Could we get support for startup probes?
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

This would make it possible to reduce the CPU set in limit (to "burst" at startup) and have better liveness checks that have a lower failureThreshold.

### PR DESCRIPTION
**Pull request by ambientsound**
Fixes #181.

### CODE REVIEW

**Comment by gtcno** [comment]
Should probably update https://github.com/nais/naisd/blob/master/nais_example.yaml as well.

**Comment by jhrv** [comment]
@gtcno naisd is dead 💀

**Comment by gtcno** [comment]
> @gtcno naisd is dead 💀

haha mybad

**Comment by ambientsound** [comment]
Documentation is up to date

https://doc.nais.io/nais-application/nais.yaml/full-example
https://doc.nais.io/nais-application/nais.yaml/reference#spec-startup

**Pull request merged**
