### PR TITLE
[Feature] Added new clusterrole to restrict permissions for naiserator

### LINKED ISSUE #17: Create ClusterRole with reduced privileges
Today, naiserator uses the `cluster-admin` role. This is too much privilege and must be constrained.

### PR DESCRIPTION
**Pull request by KFBI1706**
Fixes #17

I've created the naiserator-admin clusterrole, which get's it
permissions from a clusterroleselector. Following that I've created two
new clusterroles; one which is set to true by default, with permissions
to do everything naiserator has to do. And a conditional role that's
enabled based on if access policies are enabled for naiserator.

I've gotten the necessary permission from the api-server logs over what
naiserator has done over that last 7 months and looking through the
resorcecreator package.

It is also possible to simplify this drastically and create everything
under one clusterrole. As it's not that crucial whether or not
naiserator has access istio resouces if they don't exist.

Then again, one could argue that it is good to restrict naiserator
access to those resouces in clusters where they are available and
naiserator is not enabled for some reason.

All in all I think it's good to seperate them as it's structured better
that way and we have more fine graned control over the permissions,
which is what this whole issue is about.

### CODE REVIEW

**Comment by KFBI1706** [comment]
Refactored the clusterrole into one clusterrole and removed code logic. 
If istio is available istio should be enabled, thus removing the need for the multiple clusterroles and the code for now.

**Comment by KFBI1706** [comment]
Implemented the changes above ^^ 

The last issue is how we're going to create the new ClusterRoleBinding as well as deleting the old one. 

Maybe it should be a two part process, where we create a new ClusterRoleBinding with a different name. Delete the old one. Then rename the new one to the old one.

**Comment by ambientsound** [comment]
Renaming the roleref can be accomplished through manual deletion of the old clusterrolebinding before running the CI pipeline. We will have a few minutes of service unavailability, which is fine.

**Comment by ambientsound** [comment]
Please wait with merging this until we can coordinate.

**Pull request merged**
