### PR TITLE
Feature toggled Azurerator integration

### PR DESCRIPTION
**Pull request by ambientsound**
Suggest changes to Naiserator spec:
```
spec:
  azure:                                      # optional
    application:                              # optional
      enabled: true
      replyURLs:                              # fallback to ingresses
        - http://foo.bar/oauth/login
```

Azurerator spec looks like this:
```
---
apiVersion: nais.io/v1alpha1
kind: AzureAdApplication
metadata:
  name: myapp
  namespace: default
  labels:
    team: myteam
spec:
  preAuthorizedApplications:
    - application: myapp2
      cluster: minikube
      namespace: default
    - application: some-other-app
      cluster: test-cluster
      namespace: default
  logoutUrl: "https://localhost:3000/oauth2/logout"
  replyUrls:
    - url: "http://localhost:3000/oauth2/callback"
  secretName: azuread-myapp
```

All these fields can be auto-generated from Naiserator:
* `preAuthorizedApplications` is a verbatim copy from `.spec.accessPolicy.inbound.rules`
* `logoutUrl` is not in use and is reserved for future use, hence no Naiserator integration yet
* `replyUrls.url` can be derived from `.ingress`
* `secretName` is an internal field

### CODE REVIEW

**Comment by audunstrand** [comment]
is there sensible defaults to be user here. Or even stricter, can we make it not configurable

**Comment by jhrv** [comment]
How would we autogenerate the values if the field is optional?

**Comment by ambientsound** [comment]
Generation of defaults:

* `logoutUrl` <- `nil`
* `replyUrls` <- vector `ingress[n] + "/oauth2/callback"`

**Comment by tronghn** [comment]
Optionally, `logoutUrl` could be `ingress[0] + "/oauth2/logout"`. Although this introduces a gotcha if multiple ingresses exist. 

Unfortunately, we're subject to the restrictions laid by Microsoft/Azure where they only support a single defined logout URL for some reason.

**Comment by ambientsound** [comment]
Removed `logoutURL` from spec, see initial description.

**Pull request merged**
