### PR TITLE
action for checking for missing code gen

### LINKED ISSUE #166: Run code generation in pipeline
Pipeline should run code generation, and if it diffs against the committed code, the pipeline should fail.

We should pin the version of `controller-gen` used in the pipeline.

Refs #66

### PR DESCRIPTION
**Pull request by Kyrremann**
we don't want the action to just push the code gen, but rather that we notify the developer that they forgot

fixes #166

### CODE REVIEW

**Review by mortenlj — APPROVED** [review]
LGTM

**Review by ambientsound — APPROVED** [review]
Very nice! Can we also check for `make codegen-crd` and `make codegen-updater`?

**Comment by ambientsound** [comment]
Ironically, the test fails. These issues should be fixed in master after merging :)
LGTM!

**Comment by Kyrremann** [comment]
Isn't failing because of missing `goimport` tool?

Also, should maybe make each `make`-command a separate step?

**Comment by ambientsound** [comment]
> Isn't failing because of missing `goimport` tool?
You're right. Should be present then. It's a part of the golang/x/tools package I think?

> Also, should maybe make each `make`-command a separate step?
I don't think this is important.

**Pull request merged**
