### PR TITLE
service entries: only export to current namespace; add defaults for tokenx/idporten/azure

### LINKED ISSUE #150: ServiceEntries should only be exported to current namespace
The way it works now if *any* app has a ServiceEntry pointing to an external service, it's open for every workload in the cluster. 

https://istio.io/docs/reference/config/networking/service-entry/
```
exportTo:
  - "."
```
this would at least restrict the serviceentry to the namespace it's defined in, which makes more sense.

### PR DESCRIPTION
**Pull request by tronghn**
- Fixes #150.
- Adds default external access policy hosts to applications that have enabled `tokenx`, `idporten`, or `azuread`. 
Alternatively, we could just add ServiceEntries for all teams in nais-yaml regardless of their usage of these features (which just might be a better idea).

### CODE REVIEW

**Comment by VegarM** [comment]
Not possible yet:

https://istio.io/latest/docs/reference/config/networking/service-entry/
> NOTE: in the current release, the exportTo value is restricted to “.” or “*” (i.e., the current namespace or all namespaces).

**Comment by tronghn** [comment]
Huh. It doesn't work with `"."`? I thought that would refer to the namespace of the `ServiveEntry` resource?

**Comment by VegarM** [comment]
Thought you wanted to declare which namespaces it would apply to (misread PR title). Same namespace will work with `.`.

**Review by jhrv — APPROVED** [review]
lvgtm 🥇

**Pull request merged**
